[2025-07-18T09:21:06.982+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-18T09:21:06.987+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-07-18T02:21:00.478495+00:00 [queued]>
[2025-07-18T09:21:06.990+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2025-07-18T02:21:00.478495+00:00 [queued]>
[2025-07-18T09:21:06.990+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-18T09:21:07.005+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2025-07-18 02:21:00.478495+00:00
[2025-07-18T09:21:07.009+0700] {standard_task_runner.py:63} INFO - Started process 6324 to run task
[2025-07-18T09:21:07.011+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2025-07-18T02:21:00.478495+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpamncyj98']
[2025-07-18T09:21:07.011+0700] {standard_task_runner.py:91} INFO - Job 82: Subtask transform_load_weather_data
[2025-07-18T09:21:07.038+0700] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2025-07-18T02:21:00.478495+00:00 [running]> on host MSI.
[2025-07-18T09:21:07.099+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='menglimchea@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T02:21:00.478495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T02:21:00.478495+00:00'
[2025-07-18T09:21:07.100+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-18T09:21:09.628+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-18T09:21:09.628+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 114, in _error_wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/aiobotocore/context.py", line 36, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/aiobotocore/client.py", line 415, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow/dags/weather_dag.py", line 54, in transform_load_data
    df.to_csv(f"s3://menglim/{dt_string}.csv", index=False, storage_options=aws_credentials)
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 1930, in close
    self.flush(force=True)
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/fsspec/spec.py", line 1801, in flush
    if self._upload_chunk(final=force) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2449, in _upload_chunk
    self.commit()
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2475, in commit
    write_result = self._call_s3("put_object", **kw, **match)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 2309, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 371, in _call_s3
    return await _error_wrapper(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/menglim/airflow_venv/lib/python3.12/site-packages/s3fs/core.py", line 146, in _error_wrapper
    raise err
PermissionError: The provided token has expired.
[2025-07-18T09:21:09.638+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2025-07-18T02:21:00.478495+00:00, execution_date=20250718T022100, start_date=20250718T022106, end_date=20250718T022109
[2025-07-18T09:21:09.653+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task transform_load_weather_data (The provided token has expired.; 6324)
[2025-07-18T09:21:09.669+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-18T09:21:09.676+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-18T09:21:09.677+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
